name: build-c2a-win32
description: Build C2A user on Win32 by MSVC/MSVC++

author: '@sksat'

inputs:
  c2a_repo:
    type: string
    default: ${{ github.repository }}
  c2a_dir:
    type: string
    default: '.'
  c2a_custom_setup:
    type: string
    default: ''
  build_as_cxx:
    type: boolean
    default: false
  cmake_generator:
    type: string
    default: 'Visual Studio 17 2022'
  cmake_flags:
    type: string
    default: ''

runs:
  using: "composite"
  steps:
    - name: copy setup action
      shell: bash
      run: cp -r ${{ github.action_path }}/../action-c2a-setup /tmp/
    - name: C2A setup
      uses: /tmp/action-c2a-setup
      with:
        c2a_repo: ${{ inputs.c2a_repo }}
        c2a_dir: ${{ inputs.c2a_dir }}
        c2a_custom_setup: ${{ inputs.c2a_custom_setup }}

    - name: CMake
      if: inputs.build_as_cxx == 'false'
      working-directory: ./c2a_user
      shell: bash
      run: |
        cmake -B ./build \
          -G "${{ inputs.cmake_generator }}" \
          ${{ inputs.cmake_flags }}

    - name: CMake as C++
      if: inputs.build_as_cxx == 'true'
      working-directory: ./c2a_user
      shell: bash
      run: |
        cmake -B ./build \
          -G "${{ inputs.cmake_generator }}" \
          -DBUILD_C2A_AS_CXX=ON \
          ${{ inputs.cmake_flags }}

    - name: Build
      working-directory: ./c2a_user
      shell: bash
      run: cmake --build ./build
