name: build-c2a-win32
description: Build C2A user on Win32 by MSVC/MSVC++

author: '@sksat'

inputs:
  c2a_repo:
    type: string
    default: ${{ github.repository }}
  c2a_dir:
    type: string
    default: '.'
  c2a_custom_setup:
    type: string
    default: ''
  build_as_cxx:
    type: boolean
    default: false
  cmake_generator:
    type: string
    default: 'Visual Studio 17 2022'
  cmake_flags:
    type: string
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      if: inputs.c2a_dir == '.'
      with:
        path: ./c2a_user
        repository: ${{ inputs.c2a_repo }}
        submodules: 'recursive'
    - uses: actions/checkout@v3
      if: inputs.c2a_dir != '.'
      with:
        path: ./repo
        repository: ${{ inputs.c2a_repo }}
        submodules: 'recursive'

    - name: Setup
      shell: cmd
      run: ${{ github.action_path }}/c2a-setup.bat ${{ inputs.c2a_dir }}

    - name: Custom Setup
      if: inputs.c2a_custom_setup != ''
      working-directory: ./c2a_user
      shell: bash
      run: ${{ inputs.c2a_custom_setup }}

    - name: CMake
      if: inputs.build_as_cxx == 'false'
      working-directory: ./c2a_user
      shell: bash
      run: |
        cmake -B ./build \
          -G "${{ inputs.cmake_generator }}" \
          ${{ inputs.cmake_flags }}

    - name: CMake as C++
      if: inputs.build_as_cxx == 'true'
      working-directory: ./c2a_user
      shell: bash
      run: |
        cmake -B ./build \
          -G "${{ inputs.cmake_generator }}" \
          -DBUILD_C2A_AS_CXX=ON \
          ${{ inputs.cmake_flags }}

    - name: Build
      working-directory: ./c2a_user
      shell: bash
      run: cmake --build ./build
