name: C2A setup
description: Setup C2A user

author: '@sksat'

inputs:
  c2a_repo:
    type: string
    default: ${{ github.repository }}
  c2a_dir:
    type: string
    default: '.'
  c2a_custom_setup:
    type: string
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      if: inputs.c2a_dir == '.'
    - uses: actions/checkout@v3
      if: inputs.c2a_dir == '.'
      with:
        path: ./c2a_user
        repository: ${{ inputs.c2a_repo }}
        submodules: 'recursive'
    - uses: actions/checkout@v3
      if: inputs.c2a_dir != '.'
      with:
        path: ./repo
        repository: ${{ inputs.c2a_repo }}
        submodules: 'recursive'
    - name: Link C2A user dir to ./c2a_user
      working-directory: .
      if: inputs.c2a_dir != '.'
      shell: bash
      run: ln -s ./repo/${{ inputs.c2a_dir }} ./c2a_user

    - name: Check setup script exist
      id: check_setup
      continue-on-error: true
      working-directory: ./c2a_user
      shell: bash
      run: test -f setup.sh

    - name: Setup
      if: steps.check_setup.outcome == 'success'
      working-directory: ./c2a_user
      shell: bash
      run: ./setup.sh

    - name: Custom Setup
      if: inputs.c2a_custom_setup != ''
      working-directory: ./c2a_user
      shell: bash
      run: ${{ inputs.c2a_custom_setup }}
