name: build-c2a
description: Build C2A user

author: '@sksat'

inputs:
  c2a_repo:
    type: string
    default: ${{ github.repository }}
  gh_federation_endpoint:
    type: string
    default: ""
  federation_repos:
    type: string
    default: ""
  c2a_dir:
    type: string
    default: '.'
  c2a_custom_setup:
    type: string
    default: ''
  sils_mockup:
    type: boolean
    default: false
  build_as_cxx:
    type: boolean
    default: false
  cmake_generator:
    type: string
    default: 'Unix Makefiles'
  cmake_flags:
    type: string
    default: ''
  # reviewdog
  reviewdog_tool_name:
    type: string
    default: clang-tidy
  reviewdog_reporter:
    type: string
    default: github-pr-review
  reviewdog_filter_mode:
    type: string
    default: added

runs:
  using: "composite"
  steps:
    - name: gh-federation
      if: inputs.federation_repos != ''
      uses: arkedge/gh-federation@437d2b0433a7d4a009e311d176d18abd85626fa4 # v3.1.0
      with:
        endpoint: ${{ inputs.gh_federation_endpoint }}
        repos: ${{ inputs.federation_repos }}

    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      with:
        repository: ${{ inputs.c2a_repo }}
        submodules: 'recursive'
        path: c2a_user

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libc6-dev-i386 g++-multilib

    - name: Custom Setup
      if: inputs.c2a_custom_setup != ''
      working-directory: ./c2a_user/${{ inputs.c2a_dir }}
      shell: bash
      run: ${{ inputs.c2a_custom_setup }}

    - name: CMake
      if: inputs.build_as_cxx == 'false'
      working-directory: ./c2a_user/${{ inputs.c2a_dir }}
      shell: bash
      run: |
        cmake -B ./build \
          -G "${{ inputs.cmake_generator }}" \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DBUILD_C2A_AS_CXX=OFF \
          -DC2A_BUILD_AS_CXX=OFF \
          ${{ (inputs.sils_mockup && '-DUSE_SILS_MOCKUP=ON') || '' }} \
          ${{ inputs.cmake_flags }}

    - name: CMake as C++
      if: inputs.build_as_cxx == 'true'
      env:
        CC: clang
        CXX: clang++
      working-directory: ./c2a_user/${{ inputs.c2a_dir }}
      shell: bash
      # ignore windows.h
      run: |
        cmake -B ./build \
          -G "${{ inputs.cmake_generator }}" \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DBUILD_C2A_AS_CXX=ON \
          -DC2A_BUILD_AS_CXX=ON \
          -DUSE_SCI_COM_WINGS=OFF \
          ${{ inputs.cmake_flags }}

    - name: Build
      working-directory: ./c2a_user/${{ inputs.c2a_dir }}
      shell: bash
      run: cmake --build ./build

    - name: Run executable by SILS mockup
      if: inputs.sils_mockup == 'true'
      working-directory: ./c2a_user/${{ inputs.c2a_dir }}
      shell: bash
      run: |
        ls -lh ./build/C2A
        timeout 3 ./build/C2A || exit 0

    - name: reviewdog with clang-tidy -${{ matrix.warning }}
      if: env.CC == 'clang'
      uses: arkedge/action-clang-tidy@8657bed4bbbae3292951c06c525663b718f2fae3 # v1.2.0
      with:
        tool_name: ${{ inputs.reviewdog_tool_name }}
        reporter: ${{ inputs.reviewdog_reporter }}
        filter_mode: ${{ inputs.reviewdog_filter_mode }}
        workdir: ./c2a_user/${{ inputs.c2a_dir }}/build
