name: check encoding

on:
  workflow_call:
    inputs:
      federation_repos:
        type: string
        default: ""
      c2a_dir:
        type: string
        default: '.'
      c2a_core:
        type: boolean
        default: false
    secrets:
      GH_FEDERATION_ENDPOINT:
        required: false

env:
  # config file path from src/src_core/Script/CI
  CORE_CONFIG_FILE: check_encoding.json
  USER_CONFIG_FILE: ../../../src_user/Script/CI/check_encoding.json

jobs:
  check_encoding:
    runs-on: ubuntu-22.04
    steps:
      - name: gh-federation
        if: inputs.federation_repos != ''
        uses: arkedge/gh-federation@b70375c8a9f3d653cf7c3e00e3047eafdb33f09c # v5.0.1
        with:
          endpoint: ${{ secrets.GH_FEDERATION_ENDPOINT }}
          repos: ${{ inputs.federation_repos }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: .github/workflows/.python-version
          architecture: 'x64'

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Checkout workflows-c2a for dependency lockfile
        run: git clone --depth 1 https://github.com/arkedge/workflows-c2a.git /tmp/workflows-c2a

      - name: Install dependencies
        run: uv sync --project /tmp/workflows-c2a --no-dev

      - name: check config file
        id: config
        shell: bash
        working-directory: ${{ inputs.c2a_dir }}/src/src_core/Script/CI
        run: |
          if [ -e "$USER_CONFIG_FILE" ]; then
            echo "config_file=${USER_CONFIG_FILE}" >> "$GITHUB_OUTPUT"
          else
            echo "${USER_CONFIG_FILE} does not exist"
            echo "fallback to c2a-core config file"

            echo "config_file=${CORE_CONFIG_FILE}" >> "$GITHUB_OUTPUT"
          fi

      - name: check_encoding for c2a-core
        if: inputs.c2a_core
        working-directory: ./Script/CI
        run: uv run --project /tmp/workflows-c2a python ./check_encoding.py ./check_encoding.json
      - name: check_encoding
        if: ${{ ! inputs.c2a_core }}
        working-directory: ${{ inputs.c2a_dir }}/src/src_core/Script/CI
        run: uv run --project /tmp/workflows-c2a python ./check_encoding.py ${{ steps.config.outputs.config_file }}
