name: check coding rule

on:
  workflow_call:
    inputs:
      federation_repos:
        type: string
        default: ""
      c2a_dir:
        type: string
        default: '.'
      c2a_custom_setup:
        type: string
        default: ''
      c2a_core:
        type: boolean
        default: false
      reviewdog_version:
        type: string
        default: latest
    secrets:
      GH_FEDERATION_ENDPOINT:
        required: false

env:
  # <c2a-user> からの相対パス
  config_file: ./check_coding_rule.json
  check_script: ./src/src_core/script/ci/check_coding_rule.py

jobs:
  check_coding_rule:
    runs-on: ubuntu-24.04

    steps:
      - name: gh-federation
        if: inputs.federation_repos != ''
        uses: arkedge/gh-federation@7fcfbfdb79bad94f98041c1fb9c317b9ae198011 # v4.0.1
        with:
          endpoint: ${{ secrets.GH_FEDERATION_ENDPOINT }}
          repos: ${{ inputs.federation_repos }}

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: recursive

      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version-file: .github/workflows/.python-version
          architecture: 'x64'

      - name: Custom Setup
        if: inputs.c2a_custom_setup != ''
        working-directory: ${{ inputs.c2a_dir }}
        shell: bash
        run: ${{ inputs.c2a_custom_setup }}

      - name: check coding rule
        id: check
        shell: bash -e {0}
        continue-on-error: true
        run: |
          python ${{ inputs.c2a_dir }}/${{ env.check_script }} ${{ inputs.c2a_dir }}/${{ env.config_file }} | tee /tmp/coding-rule.log
          status="${PIPESTATUS[0]}"
          echo "status: ${status}"
          echo "status=${status}" >> "$GITHUB_OUTPUT"
          exit "${status}"

      - name: install reviewdog
        uses: reviewdog/action-setup@3f401fe1d58fe77e10d665ab713057375e39b887 # v1.3.0
        with:
          reviewdog_version: ${{ inputs.reviewdog_version }}

      - name: fix error log source file path for c2a-core
        if: inputs.c2a_core == 'true'
        run: |
          sed -i 's#${{ inputs.c2a_dir }}/src/src_core/##g' /tmp/coding-rule.log
          cat /tmp/coding-rule.log

      - name: reviewdog(github-pr-review)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog \
            -name 'check_coding_rule' \
            -level error \
            -fail-on-error=true \
            -filter-mode=added \
            -diff="git diff FETCH_HEAD" \
            -reporter=github-pr-review \
            -efm="%-GThe above files are invalid coding rule." \
            -efm="%E%f: %l: %m" \
            -efm="%C" \
            -efm="%Z%s" \
            < /tmp/coding-rule.log

      - name: exit
        shell: bash
        run: |
          exit $(( "${{ steps.check.outputs.status }}" ))
