name: CI

on:
  workflow_call:
    inputs:
      federation_repos:
        type: string
        default: ""

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      federation_repos: ${{ inputs.federation_repos }}

  check_coding_rule:
    uses: ./.github/workflows/check-coding-rule.yml

  check_encoding:
    uses: ./.github/workflows/check-encoding.yml
