name: CI

on:
  workflow_call:
    inputs:
      federation_repos:
        type: string
        default: ""
      c2a_dir:
        type: string
        default: .
      # skip gcc from build to support C89-like target
      skip_gcc:
        type: boolean
        default: false
      build_msvc:
        type: boolean
        default: false
      build_as_cxx:
        type: boolean
        default: false
      reviewdog_version:
        type: string
        default: v0.16.0
    secrets:
      GH_FEDERATION_ENDPOINT:
        required: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      federation_repos: ${{ inputs.federation_repos }}
      c2a_dir: ${{ inputs.c2a_dir }}
      skip_gcc: ${{ inputs.skip_gcc }}
      build_msvc: ${{ inputs.build_msvc }}
      build_as_cxx: ${{ inputs.build_as_cxx }}
      reviewdog_version: ${{ inputs.reviewdog_version }}

  check_coding_rule:
    secrets: inherit
    uses: ./.github/workflows/check-coding-rule.yml
    with:
      federation_repos: ${{ inputs.federation_repos }}
      c2a_dir: ${{ inputs.c2a_dir }}
      reviewdog_version: ${{ inputs.reviewdog_version }}

  check_encoding:
    secrets: inherit
    uses: ./.github/workflows/check-encoding.yml
    with:
      federation_repos: ${{ inputs.federation_repos }}
      c2a_dir: ${{ inputs.c2a_dir }}
